import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useGetLaunches from '../hooks/useGetLaunches';
import LaunchCard from '../components/LaunchCard';
import Header from '../components/Header';
import { Alert, Card } from '@mui/material';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX Launches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Content />
      </main>
    </div>
  );
}

const Content = () => {
  const { data, isLoading, error } = useGetLaunches();

  if (error)
    return (
      <Alert severity="error" data-testid="launches-error">
        Error loading launches
      </Alert>
    );

  if (isLoading)
    return (
      <div className={styles.launches}>
        {Array.from('x'.repeat(10)).map((_, i) => (
          <Card sx={{ height: 500 }} data-testid="card-loading"></Card>
        ))}
      </div>
    );

  return (
    <div className={styles.launches}>
      {data?.docs.map((launch) => (
        <LaunchCard key={launch.id} launch={launch} />
      ))}
    </div>
  );
};
